In [1]:
import numpy as np
import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import PolynomialFeatures
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_absolute_error,mean_squared_error,r2_score
import matplotlib.pyplot as plt


# Simple linear

In [3]:
#linear regression
data={
    'experience':[1,2,3,4,5,6,7,8,9,10],
    'salary':[45000,50000,60000,65000,70000,75000,80000,85000,90000,95000]
}
df=pd.DataFrame(data)
df

experience  salary
0           1   45000
1           2   50000
2           3   60000
3           4   65000
4           5   70000
5           6   75000
6           7   80000
7           8   85000
8           9   90000
9          10   95000

In [4]:
x=df[['experience']]
y=df['salary']
xtrain,xtest,ytrain,ytest=train_test_split(x,y,test_size=0.3,random_state=42)

In [5]:
regressor=LinearRegression()
regressor.fit(xtrain,ytrain)

intercept=regressor.intercept_
coeffecients=regressor.coef_

print(f"intercepts:{intercept}")
print(f"coeffiencts{coeffecients}")

ypred=regressor.predict(xtest)
print(ypred)

intercepts:42202.97029702971
coeffiencts[5383.66336634]
[90655.94059406 52970.2970297  74504.95049505]


In [6]:
mae=mean_absolute_error(ytest,ypred)
mse=mean_squared_error(ytest,ypred)
rmse=np.sqrt(mse)
r2=r2_score(ytest,ypred)

print(f'mean_absolute_error:{mae}')
print(f'mean_squared_error:{mse}')
print(f'root mean squared error:{rmse}')
print(f'r2_squared:{r2}')

mean_absolute_error:1373.762376237629
mean_squared_error:3165998.8399830223
root mean squared error:1779.325389012089
r2_squared:0.9883698001796543


# Polynomial

In [29]:
#polynomial regression
data={
    'experience':[1,2,3,4,5,6,7,8,9,10],
    'salary':[45000,50000,60000,65000,70000,75000,80000,85000,90000,95000]
}
df=pd.DataFrame(data)
df

experience  salary
0           1   45000
1           2   50000
2           3   60000
3           4   65000
4           5   70000
5           6   75000
6           7   80000
7           8   85000
8           9   90000
9          10   95000

In [30]:
x=df[['experience']]
y=df['salary']

In [31]:
polynomial_features=PolynomialFeatures(degree=2)
xpoly=polynomial_features.fit_transform(x)
xtrain,xtest,ytrain,ytest=train_test_split(xpoly,y,test_size=0.3,random_state=42)

In [32]:
regressor=LinearRegression()
regressor.fit(xtrain,ytrain)

intercept=regressor.intercept_
coeffecients=regressor.coef_

print(f"intercepts:{intercept}")
print(f"coeffiencts{coeffecients}")

ypred=regressor.predict(xtest)
print(ypred)

intercepts:39013.62260343102
coeffiencts[   0.         6961.40262361 -142.53279516]
[90121.08980827 52366.29667003 75650.85771948]


In [33]:
mae=mean_absolute_error(ytest,ypred)
mse=mean_squared_error(ytest,ypred)
rmse=np.sqrt(mse)
r2=r2_score(ytest,ypred)

print(f'mean_absolute_error:{mae}')
print(f'mean_squared_error:{mse}')
print(f'root mean squared error:{rmse}')
print(f'r2_squared:{r2}')

mean_absolute_error:1046.0813992600113
mean_squared_error:2012546.1477550447
root mean squared error:1418.6423607643487
r2_squared:0.9926069733347774


# Multivariate

In [2]:
#linear regression(multi variete)
data={
    'experience':[1,2,3,4,5,6,7,8,9,10],
    'salary':[45000,50000,60000,65000,70000,75000,80000,85000,90000,95000],
    'education':[2,2,3,3,4,4,5,5,6,6]
}

df=pd.DataFrame(data)

df

experience  salary  education
0           1   45000          2
1           2   50000          2
2           3   60000          3
3           4   65000          3
4           5   70000          4
5           6   75000          4
6           7   80000          5
7           8   85000          5
8           9   90000          6
9          10   95000          6

In [3]:
x=df[['experience','education']]
y=df['salary']

xtrain,xtest,ytrain,ytest=train_test_split(x,y,test_size=0.3,random_state=42)


In [4]:
regressor=LinearRegression()
regressor.fit(xtrain,ytrain)

intercept=regressor.intercept_
coeffecients=regressor.coef_

print(f"intercepts:{intercept}")
print(f"coeffiencts{coeffecients}")

ypred=regressor.predict(xtest)
print(ypred)

intercepts:42068.96551724138
coeffiencts[5344.82758621   86.20689655]
[90689.65517241 52931.03448276 74482.75862069]


In [6]:
mae=mean_absolute_error(ytest,ypred)
mse=mean_squared_error(ytest,ypred)
rmse=np.sqrt(mse)
r2=r2_score(ytest,ypred)

print(f'mean_absolute_error:{mae}')
print(f'mean_squared_error:{mse}')
print(f'root mean squared error:{rmse}')
print(f'r2_squared:{r2}')

mean_absolute_error:1379.3103448275845
mean_squared_error:3111375.346809356
root mean squared error:1763.9091095658405
r2_squared:0.9885704579096799
